### Imports

In [12]:
import numpy as np
from pathlib import Path
import pandas as pd
from sklearn.utils import shuffle

In [13]:
ROOT_PATH = Path().absolute().parent
ROOT_PATH

PosixPath('/Users/ingridturkerud/Desktop/TDT4900-Master-Thesis')

In [14]:
para_path = ROOT_PATH.joinpath('data', 'external', 'p5.csv')

In [15]:
coco_path = ROOT_PATH.joinpath('data', 'processed', 'karpathy_split', 'c5_train_clean.csv')

In [23]:
SEED = 12345
np.random.seed(SEED)

In [9]:
para_df = pd.read_csv(para_path)
para_df

,Unnamed: 0,image_id,image_name,caption_id,caption
0,0,1,COCO_val2014_000000522418.jpg,COCO_val2014_000000522418#693204#p,A woman striking a cake with the back of the c...
1,1,1,COCO_val2014_000000522418.jpg,COCO_val2014_000000522418#688839#p,A woman wearing a hair cut net a big cake of t...
2,2,1,COCO_val2014_000000522418.jpg,COCO_val2014_000000522418#693159#p,there is a woman who cut a white cake
3,3,1,COCO_val2014_000000522418.jpg,COCO_val2014_000000522418#686718#p,A woman cutting a cake big white sheet.
4,4,1,COCO_val2014_000000522418.jpg,COCO_val2014_000000522418#681330#p,A woman wearing a head net on the cake.
...,...,...,...,...,...
566280,566280,123286,COCO_train2014_000000475546.jpg,COCO_train2014_000000475546#8002#p,Group of people drinking wine in a public place.
566281,566281,123286,COCO_train2014_000000475546.jpg,COCO_train2014_000000475546#5620#p,People having a drink in a basement bar.
566282,566282,123286,COCO_train2014_000000475546.jpg,COCO_train2014_000000475546#283#p,Customers enjoy their drinks at the bar.
566283,566283,123286,COCO_train2014_000000475546.jpg,COCO_train2014_000000475546#5716#p,a group of friends enjoy a drink while sitting...
566284,566284,123286,COCO_train2014_000000475546.jpg,COCO_train2014_000000475546#9277#p,three women and a man are sitting at a bar

In [10]:
coco_df = pd.read_csv(coco_path)
coco_df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,image_id,image_name,caption_id,caption,clean_caption
0,0,0,4,4,4,1,COCO_val2014_000000522418.jpg,COCO_val2014_000000522418#693204,A woman marking a cake with the back of a chef...,startseq a woman marking a cake with the back ...
1,1,1,2,2,2,1,COCO_val2014_000000522418.jpg,COCO_val2014_000000522418#688839,A woman wearing a hair net cutting a large she...,startseq a woman wearing a hair net cutting a ...
2,2,2,3,3,3,1,COCO_val2014_000000522418.jpg,COCO_val2014_000000522418#693159,there is a woman that is cutting a white cake,startseq there is a woman that is cutting a wh...
3,3,3,1,1,1,1,COCO_val2014_000000522418.jpg,COCO_val2014_000000522418#686718,A woman cutting a large white sheet cake.,startseq a woman cutting a large white sheet c...
4,4,4,0,0,0,1,COCO_val2014_000000522418.jpg,COCO_val2014_000000522418#681330,A woman wearing a net on her head cutting a ca...,startseq a woman wearing a net on her head cut...
...,...,...,...,...,...,...,...,...,...,...
566280,566280,566280,566283,566715,566745,123286,COCO_train2014_000000475546.jpg,COCO_train2014_000000475546#8002,Group of people drinking wine at a public loca...,startseq group of people drinking wine at a pu...
566281,566281,566281,566281,566713,566743,123286,COCO_train2014_000000475546.jpg,COCO_train2014_000000475546#5620,People having a drink in a basement bar.,startseq people having a drink in a basement b...
566282,566282,566282,566280,566712,566742,123286,COCO_train2014_000000475546.jpg,COCO_train2014_000000475546#283,The patrons enjoy their beverages at the bar.,startseq the patrons enjoy their beverages at ...
566283,566283,566283,566282,566714,566744,123286,COCO_train2014_000000475546.jpg,COCO_train2014_000000475546#5716,A group of friends enjoys a drink while sittin...,startseq a group of friends enjoys a drink whi...
566284,566284,566284,566284,566716,566746,123286,COCO_train2014_000000475546.jpg,COCO_train2014_000000475546#9277,Three women and a man are sitting at a bar,startseq three women and a man are sitting at ...

In [17]:
SAMPLE_SIZE=20

In [24]:
shuff = shuffle(para_df)
shuff = shuff.reset_index(drop=True)
p_sample = shuff.loc[:SAMPLE_SIZE-1, ['caption_id', 'caption']]
p_sample

,caption_id,caption
0,COCO_train2014_000000522244#679254#p,Some beautiful trains in search of a small sta...
1,COCO_train2014_000000278291#612356#p,This is a picture with a bathroom scene.
2,COCO_val2014_000000044612#106368#p,A woman standing next to a horse in a field.
3,COCO_train2014_000000251405#696637#p,there is a man standing at a table with a big ...
4,COCO_train2014_000000414822#694719#p,people waiting for their luggage in a baggage ...
5,COCO_val2014_000000062817#556920#p,a person holding a cell phone
6,COCO_train2014_000000551284#470042#p,a hand is near the switch of a large orange an...
7,COCO_train2014_000000328023#554783#p,A woman with her mouth open and holding a Fris...
8,COCO_train2014_000000396284#666096#p,a white sheet covered with uncooked chicken pi...
9,COCO_train2014_000000421759#294848#p,a smiling woman on a sofa has a laptop.
10,COCO_val2014_000000122994#439070#p,An umbrella is shown open under the trees.
11,COCO_train2014_000000519320#791128#p,Man sitting in a window talking on a cell phone
12,COCO_train2014_000000579186#720104#p,there is a room with a fireplace and sofas.
13,COCO_train2014_000000465266#204636#p,A stop sign with another sign below position...
14,COCO_train2014_000000174521#395607#p,An old fashioned picture of a man wearing a tu...
15,COCO_train2014_000000065420#615165#p,a lively crowd seeking shelter from the rain u...
16,COCO_train2014_000000134769#727767#p,a very large pizza loaded with assorted toppings.
17,COCO_train2014_000000020903#808993#p,a clean bathroom is seen in this image.
18,COCO_train2014_000000492382#190272#p,four yellow and white red bikes a building and...
19,COCO_train2014_000000238177#471553#p,a lounge with sofas and a dining table

In [26]:
## find the orignial captions in coco_df
sample_d = {}
for i in range(len(p_sample)):
    caption_id = p_sample.loc[i, 'caption_id']
    caption = p_sample.loc[i, 'caption']
    sample_d[caption_id] = caption

In [27]:
for i in range(len(coco_df)):
    image_name = coco_df.loc[i, 'image_name']
    cap_id = coco_df.loc[i, 'caption_id']
    cap = coco_df.loc[i, 'caption']
    # locate the paraphrase
    candidate = cap_id+'#p'
    if candidate in sample_d:
        print('OG:\t' + str(cap) + '\tPARA:\t' + str(sample_d[candidate]))

OG:	An umbrella is shown open under the trees.	PARA:	An umbrella is shown open under the trees.
OG:	A woman standing next to a horse in a field.	PARA:	A woman standing next to a horse in a field.
OG:	a person holds on to a cell phone 	PARA:	a person holding a cell phone
OG:	A hand is near the switch of a large orange and white blender.	PARA:	a hand is near the switch of a large orange and white mixer.
OG:	four yellow red and white bicycles a building and some trees	PARA:	four yellow and white red bikes a building and some trees
OG:	there is a man that is standing at a table with a large cake	PARA:	there is a man standing at a table with a big cake
OG:	A stop sign with another sign under it, positioned on a street, next to a us stop.	PARA:	A stop sign with another sign below   positioned on a street next to a stop.
OG:	A woman with her mouth open and holding a frisbee in her hands. 	PARA:	A woman with her mouth open and holding a Frisbee in his hands.
OG:	There is a room with a fireplace and couches.	PARA:	there is a room with a fireplace and sofas.
OG:	That is an image with a bathroom scene.
	PARA:	This is a picture with a bathroom scene.
OG:	A bustling crowd seeking shelter from the rain under umbrellas.	PARA:	a lively crowd seeking shelter from the rain under umbrellas.
OG:	a living room with some couches and a dinning table 	PARA:	a lounge with sofas and a dining table
OG:	A smiling woman on a couch has a laptop computer.	PARA:	a smiling woman on a sofa has a laptop.
OG:	Some very nice looking trains by a small station.	PARA:	Some beautiful trains in search of a small station.
OG:	A man sitting in a window talking on a cell phone	PARA:	Man sitting in a window talking on a cell phone
OG:	A clean bathroom is seen in this image.	PARA:	a clean bathroom is seen in this image.
OG:	An old fashioned picture of a man wearing a tuxedo. 	PARA:	An old fashioned picture of a man wearing a tuxedo.
OG:	A very big pizza loaded with assorted toppings.	PARA:	a very large pizza loaded with assorted toppings.
OG:	People wait for their baggage at an airport baggage claim area.	PARA:	people waiting for their luggage in a baggage area airport.
OG:	A white plate covered in pieces of uncooked chicken.	PARA:	a white sheet covered with uncooked chicken pieces.